title: 
description: ""
url: https://faenuccio-teaching.github.io
baseurl: "/M1_ENS_26"
repository: faenuccio-teaching/M1_ENS_26

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

keep_files:
  - docs
  - docbuild

show_downloads: true

nav:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: Pr√©requis Lean et GitHub
    url: /index.html#prerequis-lean-et-github
  - title: GitHub
    url: https://github.com/faenuccio-teaching/M1_ENS_26
